### ISSUE TITLE
Absence of releases

### ISSUE THREAD

**Issue by advancingu** [heidelpay/heidelpayNodeJS#90]
There have currently been [42 commits](https://github.com/heidelpay/heidelpayNodeJS/compare/1.2.5...develop) to `devel`, including bugfixes and functionality additions, since the last official release of this package 14 months ago.

When can the next release be expected that officially makes these changes available?

**Comment by KhangVu-nfq-asia** [comment]
Hi @advancingu,
Thanks for your question. 
I would assume that you are tracing our release by checking on Github. And it's mention we are at v1.2.5.
Sorry for let this confuse you, but we are using npm package as a release version control.

And you should find it in the very first line in our README.md. You can also check it here: https://www.npmjs.com/package/@heidelpay/nodejs-sdk
And officially, we are now at v1.3.1.

Hope this is helpful for you and thank you.

**Comment by advancingu** [comment]
Ok, thanks. :+1:
